# Generated by Django 2.2 on 2019-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=400)),
                ('body', models.TextField()),
                ('video', models.URLField(max_length=400)),
            ],
        ),
    ]
