# Generated by Django 2.2 on 2019-04-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20190408_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects_model',
            name='url',
        ),
        migrations.RemoveField(
            model_name='projects_model',
            name='video',
        ),
    ]
