# Generated by Django 2.2 on 2019-04-17 21:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20190408_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_model',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
