# Generated by Django 2.2 on 2019-04-13 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_name',
            field=models.CharField(default='kazifarhanuddin', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='Github_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=800)),
                ('discription', models.TextField()),
                ('languages', models.CharField(max_length=800)),
                ('created_at', models.DateField()),
                ('size', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
