# Generated by Django 2.2 on 2019-04-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190413_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github_model',
            name='size',
        ),
    ]
