# Generated by Django 2.2 on 2019-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_github_model_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='github_model',
            name='starts',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
