# Generated by Django 2.2 on 2019-04-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_github_model_starts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github_model',
            old_name='starts',
            new_name='stars',
        ),
    ]
