# Generated by Django 2.2 on 2019-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20190414_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github_model',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
